export const dataDeVehiculos = [
  {
    nombre: 'Ford F100',
    proximoCambio: '105900km',
    fechaProximoCambio: '10-08-2023',
    comentario: '',
    link: 'https://drive.google.com/drive/folders/1xvcaQM34ojaXJEB1iJxsXQV26AR7lo7a?usp=sharing',
  },

  {
    nombre: 'Grupo extrusores',
    proximoCambio: '610hs',
    fechaProximoCambio: '25-02-2023',
    comentario: '',
    link: 'https://drive.google.com/drive/folders/12u-i64HDN3hPGbifcGSrlDU9O8YIcgZ3?usp=sharing',
  },
  {
    nombre: 'Grupo gallineros motor John Deere',
    proximoCambio: '319hs',
    fechaProximoCambio: '24-02-2023',
    comentario: '',
    link: 'https://drive.google.com/drive/folders/1Y3AxsyJP62cww2vmU2Q33rx9tkWx09sJ?usp=sharing',
  },
  {
    nombre: 'Grupo gallineros motor internacional',
    proximoCambio: '471hs',
    fechaProximoCambio: '25-02-2023',
    comentario: '',
    link: 'https://drive.google.com/drive/folders/1qqH1fy5nMNksLYWWWOoZjzgtDCG09Cg9?usp=sharing',
  },
  {
    nombre: 'Massey  1670',
    proximoCambio: '1250hs',
    fechaProximoCambio: '27-08-2023',
    comentario: 'Prox cambiar aceite reductores',
    link: 'https://drive.google.com/drive/folders/10Z3piR3MiAYeCDs7B4L6uqidHJqfuVWV?usp=sharing',
  },
  {
    nombre: 'Massey 4297',
    proximoCambio: '6580hs',
    comentario: 'Prox cambiar filtro combustible',
    fechaProximoCambio: '05-07-2023',
    link: 'https://drive.google.com/drive/folders/1KeLv38lfUafOaHYYe3AxmVQumNo5Fl0c?usp=sharing',
  },
  {
    nombre: 'Massey 7140',
    proximoCambio: '4467hs',
    fechaProximoCambio: '01-06-2023',
    comentario: 'Prox cambiar filtro gasoil, estan en stock',
    link: 'https://drive.google.com/drive/folders/1f3pG9KthDZhzyiONU8uV0o1OYKXt1lju?usp=sharing',
  },
  {
    nombre: 'Massey 6712 (Power Shuttle)',
    proximoCambio: '1000hs',
    fechaProximoCambio: '****',
    comentario: 'Realizado con 800hs en concesionario',
    link: 'https://drive.google.com/drive/folders/1lteIqkj_jrUboFQzui9C3pnctyGVGtIA?usp=sharing',
  },
  {
    nombre: 'Massey viejo',
    proximoCambio: '1200hs',
    fechaProximoCambio: '24-08-2022',
    comentario: '',
    link: 'https://drive.google.com/drive/folders/1_MVoUZMIUXP1Mks7aZiN1XUKl0HP670J?usp=sharing',
  },
  {
    nombre: 'Mercedes volcador',
    proximoCambio: '340hs',
    fechaProximoCambio: '07-06-2023',
    comentario: '',
    link: 'https://drive.google.com/drive/folders/1EMjsNMAe1WenQOAxp8UdYT4AawfdgpxM?usp=sharing',
  },
  {
    nombre: 'Pala Aeolite',
    proximoCambio: '9227hs',
    fechaProximoCambio: '04-05-2022',
    comentario: '',
    link: 'https://drive.google.com/drive/folders/1gzvFEuaBfOD-4E_2UOScmPSoryWv8zh9?usp=sharing',
  },
  {
    nombre: 'Sprinter Dut-36*',
    proximoCambio: '8010hs',
    fechaProximoCambio: '29-12-2022',
    comentario: '',
    link: 'https://drive.google.com/drive/folders/1ti7Uz06XT_a4VlSvIMkoDqpveghaC2vP?usp=sharings',
  },
  {
    nombre: 'Valtra',
    proximoCambio: '5063 hs',
    fechaProximoCambio: '****',
    comentario: 'Controlar aceites diferencial y caja',
    link: 'https://drive.google.com/drive/folders/1ay9IBNS0cg-Czq5FpLF1vs6GB285xfeV?usp=sharing',
  },
  {
    nombre: 'Volvo iiy-74*',
    proximoCambio: '713648km',
    fechaProximoCambio: '07-04-2023',
    comentario: '',
    link: 'https://drive.google.com/drive/folders/1fDwojaOUVtmfFUzHXEcKKW9crPtyIfX8?usp=sharing',
  },
  {
    nombre: 'Volvo ad695**',
    proximoCambio: '132672km',
    comentario: '',
    fechaProximoCambio: '16-04-2023',
    link: 'https://drive.google.com/drive/folders/1xxhuzADUWA-F_M1KHt6vbBR8YiuIQYKU?usp=sharing',
  },
  {
    nombre: 'Volvo ab969**',
    proximoCambio: '374382km',
    fechaProximoCambio: '29-04-2023',
    comentario: 'Cambió filtro secante en mecanico',
    link: 'https://drive.google.com/drive/folders/1BxUgoI39s6RlNdcQzoqUErPkFRrsXnks?usp=sharing',
  },

  {
    nombre: 'Mixer c/protector caja',
    proximoCambio: '****',
    fechaProximoCambio: '11-08-2023',
    comentario: 'caja delantera 10L 80w90, caja trasera sae250',
    link: null,
  },
  {
    nombre: 'Mixer s/protector caja',
    proximoCambio: '****',
    fechaProximoCambio: '11-08-2023',
    comentario: 'caja delantera 10L 80w90, caja trasera sae250',
    link: null,
  },
  {
    nombre: 'Nissan Frontier jhp-7**',
    proximoCambio: '277000km',
    fechaProximoCambio: '29-08-2023',
    comentario: '',
    link: 'https://drive.google.com/drive/folders/1eWKiQ5VjpTOiXW9l_s9TqlQfd1Ocx4qC',
  },
  {
    nombre: 'Volvo hju-528',
    proximoCambio: '560030km',
    fechaProximoCambio: '07-06-2023',
    comentario: '',
    link: 'https://docs.google.com/spreadsheets/d/1fsgqIisTxh9Hwnt63kI4rfXcyiz9aufs/edit#gid=35771524',
  },
];
