export const vehicle_data = [
  {
    name: 'Nissan frontier FDM-9*5',
    nextChange: '330700km',
    nextChangeDate: '07-02-2024',
    comment: 'Prox cambiar aceite diferenciales y caja de cambios',
    link: '',
  },
  {
    name: 'Ford F100',
    nextChange: '105900km',
    nextChangeDate: '10-08-2023',
    comment: '',
    link: 'https://drive.google.com/drive/folders/1xvcaQM34ojaXJEB1iJxsXQV26AR7lo7a?usp=sharing',
  },
  {
    name: 'Sprinter Pasajeros',
    nextChange: '8621hs',
    nextChangeDate: '23-09-2023',
    comment: '',
    link: 'https://drive.google.com/drive/folders/1HkBC6R-8vb8GoGJp5_9A_5yilHMmWHap?hl=es',
  },
  {
    name: 'Pala LonKing',
    nextChange: '735hs',
    nextChangeDate: '03-10-2023',
    comment: '',
    link: 'https://drive.google.com/drive/folders/19LoHptRz9ey26ds6kHXQDBnSrlIORHSr?hl=es',
  },

  {
    name: 'Grupo extrusores',
    nextChange: '641hs',
    nextChangeDate: '23-02-2024',
    comment: 'Prox cambiar filtros de aire',
    link: 'https://drive.google.com/drive/folders/12u-i64HDN3hPGbifcGSrlDU9O8YIcgZ3?usp=sharing',
  },
  {
    name: 'Grupo gallineros motor John Deere',
    nextChange: '252hs',
    nextChangeDate: '23-02-2024',
    comment: 'FUERA DE SERVICIO',
    link: 'https://drive.google.com/drive/folders/1Y3AxsyJP62cww2vmU2Q33rx9tkWx09sJ?usp=sharing',
  },
  {
    name: 'Grupo gallineros motor internacional',
    nextChange: '471hs',
    nextChangeDate: '25-02-2023',
    comment: '',
    link: 'https://drive.google.com/drive/folders/1qqH1fy5nMNksLYWWWOoZjzgtDCG09Cg9?usp=sharing',
  },
  {
    name: 'Massey  1670',
    nextChange: '1250hs',
    nextChangeDate: '27-08-2023',
    comment: 'Prox cambiar aceite reductores',
    link: 'https://drive.google.com/drive/folders/10Z3piR3MiAYeCDs7B4L6uqidHJqfuVWV?usp=sharing',
  },
  {
    name: 'Massey 4297',
    nextChange: '6850hs',
    comment: 'Prox cambiar filtro combustible',
    nextChangeDate: '11-02-2024',
    link: 'https://drive.google.com/drive/folders/1KeLv38lfUafOaHYYe3AxmVQumNo5Fl0c?usp=sharing',
  },
  {
    name: 'Massey 7140',
    nextChange: '4467hs',
    nextChangeDate: '01-06-2023',
    comment: 'Prox cambiar filtro gasoil, estan en stock',
    link: 'https://drive.google.com/drive/folders/1f3pG9KthDZhzyiONU8uV0o1OYKXt1lju?usp=sharing',
  },
  {
    name: 'Massey 6712 (Power Shuttle)',
    nextChange: '1586hs',
    nextChangeDate: '04-09-2023',
    comment: 'Prox cambiar filtros gasoil',
    link: 'https://drive.google.com/drive/folders/1lteIqkj_jrUboFQzui9C3pnctyGVGtIA?usp=sharing',
  },
  {
    name: 'Massey viejo',
    nextChange: '2600hs',
    nextChangeDate: '03-02-2024',
    comment: '',
    link: 'https://drive.google.com/drive/folders/1_MVoUZMIUXP1Mks7aZiN1XUKl0HP670J?usp=sharing',
  },
  {
    name: 'Mercedes volcador',
    nextChange: '574hs',
    nextChangeDate: '27-10-2023',
    comment: 'Reparación radiador',
    link: 'https://drive.google.com/drive/folders/1EMjsNMAe1WenQOAxp8UdYT4AawfdgpxM?usp=sharing',
  },
  {
    name: 'Pala Aeolite',
    nextChange: '9227hs',
    nextChangeDate: '04-05-2022',
    comment: '',
    link: 'https://drive.google.com/drive/folders/1gzvFEuaBfOD-4E_2UOScmPSoryWv8zh9?usp=sharing',
  },
  {
    name: 'Sprinter Dut-36*',
    nextChange: '8010hs',
    nextChangeDate: '29-12-2022',
    comment: '',
    link: 'https://drive.google.com/drive/folders/1ti7Uz06XT_a4VlSvIMkoDqpveghaC2vP?usp=sharings',
  },
  {
    name: 'Valtra',
    nextChange: '5300 hs',
    nextChangeDate: '30-11-2023',
    comment: 'Prox cambiar filtros gasoil',
    link: 'https://drive.google.com/drive/folders/1ay9IBNS0cg-Czq5FpLF1vs6GB285xfeV?usp=sharing',
  },
  {
    name: 'Volvo iiy-74*',
    nextChange: '713648km',
    nextChangeDate: '07-04-2023',
    comment: '',
    link: 'https://drive.google.com/drive/folders/1fDwojaOUVtmfFUzHXEcKKW9crPtyIfX8?usp=sharing',
  },
  {
    name: 'Volvo ad695**',
    nextChange: '173632km',
    comment: 'Prox cambiar filtros gasoil, y aceite caja y diferencial',
    nextChangeDate: '16-02-2024',
    link: 'https://drive.google.com/drive/folders/1xxhuzADUWA-F_M1KHt6vbBR8YiuIQYKU?usp=sharing',
  },
  {
    name: 'Volvo ab969**',
    nextChange: '463000km',
    nextChangeDate: '28-1-2024',
    comment: 'Prox no cambiar filtros gasoil',
    link: 'https://drive.google.com/drive/folders/1BxUgoI39s6RlNdcQzoqUErPkFRrsXnks?usp=sharing',
  },

  {
    name: 'Mixer c/protector caja',
    nextChange: '****',
    nextChangeDate: '11-08-2023',
    comment: 'caja delantera 10L 80w90, caja trasera sae250',
    link: null,
  },
  {
    name: 'Mixer s/protector caja',
    nextChange: '****',
    nextChangeDate: '11-08-2023',
    comment: 'caja delantera 10L 80w90, caja trasera sae250',
    link: null,
  },
  {
    name: 'Nissan Frontier jhp-7**',
    nextChange: '277000km',
    nextChangeDate: '29-08-2023',
    comment: 'Prox cambiar aceites cajas y diferencial',
    link: 'https://drive.google.com/drive/folders/1eWKiQ5VjpTOiXW9l_s9TqlQfd1Ocx4qC',
  },
  {
    name: 'Volvo hju-52*',
    nextChange: '560030km',
    nextChangeDate: '07-06-2023',
    comment: '',
    link: 'https://docs.google.com/spreadsheets/d/1fsgqIisTxh9Hwnt63kI4rfXcyiz9aufs/edit#gid=35771524',
  },
];
